name: Jekyll Site CI

on:
  push:
    branches: [ "main" ] # Replace with your default branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
            --rm \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest \
            /bin/bash -c "bundle install && jekyll build --future"

      - name: Deploy to GitHub Pages (if applicable)
        uses: actions/deploy@v1
        with:
          repository_nwo: ${{ github.repository }}
          artifact_path: ./_site
